import 'bootstrap/dist/css/bootstrap.min.css'
import "./globals.css"
import type { Metadata } from "next"
import { Card, CardHeader, CardBody } from 'react-bootstrap'
import Container from "react-bootstrap/Container"

export const metadata: Metadata = {
  title: "Color Playground",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Container className="center mt-5">
          <Card>
            <CardHeader className="text-center">
              <h1>Color Playground</h1>
            </CardHeader>
            <CardBody>
              {children}
            </CardBody>
          </Card>
        </Container>
      </body>
    </html>
  )
}
