import 'bootstrap/dist/css/bootstrap.min.css'
import './globals.css'
import React from 'react'
import type { Metadata } from 'next'
import { Card, CardHeader, CardBody } from 'react-bootstrap'
import Container from 'react-bootstrap/Container'
import DarkModeToggle from '@/components/DarkModeToggle'

export const metadata: Metadata = {
  title: 'Color Playground',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <div className="toggle-container">
          <DarkModeToggle />
        </div>
        <Container className="center h-100">
          <Card>
            <CardHeader className="text-center">
              <h1>Color Playground</h1>
            </CardHeader>
            <CardBody>
              {children}
            </CardBody>
          </Card>
        </Container>
      </body>
    </html>
  )
}
