import 'bootstrap/dist/css/bootstrap.min.css'
import './globals.css'
import style from './main.module.css'
import React from 'react'
import type { Metadata } from 'next'
import { Card, Container, CardHeader, CardBody } from 'react-bootstrap'
import DarkModeToggle from '@/components/DarkModeToggle'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Color Playground',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <div className={style.toggleContainer}>
          <DarkModeToggle />
        </div>
        <Container className={style.container}>
          <Card>
            <CardHeader className="text-center">
              <h1>Color Playground</h1>
            </CardHeader>
            <CardBody>
              {children}
            </CardBody>
          </Card>
        </Container>
        <Footer />
      </body>
    </html>
  )
}
